#### analyzing one reach sample

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [31]:
# general info per trial (contains multiple reaches per trial)
block_info = pd.read_csv("../../Data Extraction/Extracted Data/MM_S1_processed/block_info/block_info.csv")

In [7]:
block_info.head()

,TrialStartTime,Target1AppearanceTime,Target1MovementOnsetTime,Target1PeakVelocityTime,Target1XLocation,Target1YLocation,Target2AppearanceTime,Target2MovementOnsetTime,Target2PeakVelocityTime,Target2XLocation,...,Target3PeakVelocityTime,Target3XLocation,Target3YLocation,Target4AppearanceTime,Target4MovementOnsetTime,Target4PeakVelocityTime,Target4XLocation,Target4YLocation,TrialEndTime,TrialResult
0,23.890833,23.992067,24.185,24.444,1.805732,-4.219038,24.834167,25.066,25.281,-3.679024,...,26.246,1.028914,-7.127864,26.612600,26.773,27.070,5.732509,-8.823799,27.373467,82
1,31.920767,32.022033,32.305,32.465,-1.082157,-4.040896,33.090667,33.288,33.562,5.441960,...,34.290,5.037742,-0.658798,34.560333,34.713,34.916,0.083082,0.013026,35.424467,82
2,36.427967,36.529200,36.530,50.026,-5.684660,-6.150695,50.425733,50.579,50.751,-1.321916,...,51.749,3.360862,-5.460654,52.025700,52.212,52.475,7.920916,-7.511484,52.792600,82
3,53.796100,53.897333,54.199,54.384,3.043444,-6.411366,54.773533,54.889,55.178,-3.347823,...,55.915,1.589487,-1.023291,56.241167,56.444,56.759,8.748001,-3.890110,57.034133,82
4,58.037633,58.138867,58.391,58.666,8.532041,1.105224,59.353900,59.522,59.726,5.610942,...,NaN,1.112203,6.684224,61.140333,61.352,61.535,-3.467990,8.689672,61.910233,82

In [30]:
block_info.describe()

,TrialStartTime,Target1AppearanceTime,Target1MovementOnsetTime,Target1PeakVelocityTime,Target1XLocation,Target1YLocation,Target2AppearanceTime,Target2MovementOnsetTime,Target2PeakVelocityTime,Target2XLocation,...,Target3PeakVelocityTime,Target3XLocation,Target3YLocation,Target4AppearanceTime,Target4MovementOnsetTime,Target4PeakVelocityTime,Target4XLocation,Target4YLocation,TrialEndTime,TrialResult
count,140.000000,140.000000,124.000000,124.000000,140.000000,140.000000,140.000000,135.000000,135.000000,140.000000,...,137.000000,140.000000,140.000000,140.000000,138.000000,138.000000,140.000000,140.000000,140.000000,140.0
mean,530.047986,530.149235,532.784452,533.210710,-0.184294,-0.199499,531.882549,537.626785,537.925556,-0.548482,...,540.124876,0.100556,-0.197945,533.542772,533.760623,534.033145,0.432829,-0.118572,534.275735,82.0
std,284.163236,284.163236,285.606865,285.465043,4.826803,4.852062,284.216974,281.552327,281.550334,4.226411,...,281.726628,4.434436,4.760298,284.221268,286.184709,286.192461,4.876067,4.653709,284.232571,0.0
min,23.890833,23.992067,24.185000,24.444000,-8.993824,-8.897456,24.834167,25.066000,25.281000,-8.971837,...,26.246000,-8.989765,-8.877297,26.612600,26.773000,27.070000,-8.822865,-8.823799,27.373467,82.0
25%,292.319708,292.420950,297.008750,297.257750,-3.641362,-4.160071,293.293633,301.083500,301.428000,-3.462722,...,300.412000,-3.069696,-3.939216,295.084567,293.019000,293.301500,-3.688237,-3.630699,295.811383,82.0
50%,543.708783,543.810050,545.947000,546.234000,-0.307746,-0.068514,546.706233,553.497000,553.926000,-0.779249,...,554.507000,0.720341,-0.355031,548.432033,548.517500,548.838500,0.576510,-0.382231,549.059567,82.0
75%,756.623325,756.724592,766.453500,766.561250,3.826378,3.585115,760.128808,761.320500,761.660000,2.399319,...,764.509000,3.564576,3.566766,761.764617,763.927250,764.431000,4.343873,3.911124,762.501675,82.0
max,1024.375567,1024.476800,1024.767000,1024.955000,8.532041,8.986864,1025.315900,1025.513000,1025.703000,8.915013,...,1026.379000,8.747383,8.914492,1026.882767,1027.053000,1027.397000,8.748001,8.689672,1027.705833,82.0

In [19]:
dataframes = {}

for file in os.listdir("reach example"):
    if file.endswith(".csv"):  # Ensure it's a CSV file
        file_path = os.path.join("reach example", file)
        df_name = f"{file[:-4]}_df"
        dataframes[df_name] = pd.read_csv(file_path)

In [33]:
# info on data in each df
for df in dataframes:
    print(df)
    print(dataframes[df].shape)

target_on_reach1_df
(97, 1)
trial_num_reach1_df
(1, 1)
cue_on_reach1_df
(1, 1)
reach_dir_reach1_df
(1, 1)
reach_pos_end_reach1_df
(1, 2)
reach_st_reach1_df
(1, 1)
neural_data_PMd_reach1_df
(97, 95)
reach_pos_st_reach1_df
(1, 2)
time_window_reach1_df
(418, 1)
reach_len_reach1_df
(1, 1)
timestamps_reach1_df
(97, 1)
reach_end_reach1_df
(1, 1)
reach1_df
(97, 7)
reach_num_reach1_df
(1, 1)

In [60]:
# Assuming 'dataframes' is your dictionary of DataFrames
single_row_dfs = [
    "trial_num_reach1_df", "reach_num_reach1_df", "cue_on_reach1_df", "reach_st_reach1_df", "reach_end_reach1_df",  
    "reach_pos_st_reach1_df", "reach_pos_end_reach1_df", "reach_dir_reach1_df", "reach_len_reach1_df"   
]

# Concatenate single-row DataFrames horizontally
trial_info_df = pd.concat([dataframes[df] for df in single_row_dfs], axis=1)

In [61]:
trial_info_df

,TrialNumber,ReachNumber,CueOnTime,ReachStartTime,ReachEndTime,StartPositionX,StartPositionY,EndPositionX,EndPositionY,ReachDirection,ReachLength
0,1,1,24.088067,24.088067,24.75,-3.338924,1.726462,-1.010119,-2.192063,-1.034574,4.558308

In [62]:
# Assuming 'dataframes' is your dictionary of DataFrames
# only one left is "time_window_reach1_df", which just has which time windows correspond to the reach, this should already be in time stamps though
time_dfs = [
    "timestamps_reach1_df", "neural_data_PMd_reach1_df", 
     "reach1_df", "target_on_reach1_df"
]

# Concatenate single-row DataFrames horizontally
time_bin_df = pd.concat([dataframes[df] for df in time_dfs], axis=1)

In [63]:
time_bin_df.head()

,TimeStamp,TimeBin,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,...,Neuron93,Neuron94,x_position,y_position,x_velocity,y_velocity,x_acceleration,y_acceleration,time_stamps,TargetOn
0,23.79,1,0,0,0,0,0,0,0,0,...,0,0,-3.528073,1.246197,-0.058506,-0.091257,-27.356562,-17.469933,23.79,0
1,23.80,2,0,0,0,0,0,0,0,0,...,0,0,-3.528866,1.245791,-0.022758,0.039102,23.217614,13.524994,23.80,0
2,23.81,3,0,0,0,0,0,0,0,0,...,0,0,-3.528202,1.245970,0.080537,-0.041023,-12.605531,-10.911118,23.81,0
3,23.82,4,0,0,0,0,0,0,0,0,...,0,0,-3.528681,1.245885,-0.140814,0.072169,-6.628672,17.104540,23.82,0
4,23.83,5,0,0,0,0,0,0,0,0,...,0,0,-3.528435,1.245922,0.280550,-0.193932,67.613019,-62.822279,23.83,0

In [47]:
# time stamps are in this as well
dataframes["reach1_df"].head()

,x_position,y_position,x_velocity,y_velocity,x_acceleration,y_acceleration,time_stamps
0,-3.528073,1.246197,-0.058506,-0.091257,-27.356562,-17.469933,23.79
1,-3.528866,1.245791,-0.022758,0.039102,23.217614,13.524994,23.80
2,-3.528202,1.245970,0.080537,-0.041023,-12.605531,-10.911118,23.81
3,-3.528681,1.245885,-0.140814,0.072169,-6.628672,17.104540,23.82
4,-3.528435,1.245922,0.280550,-0.193932,67.613019,-62.822279,23.83

In [64]:
# verified that time_stamps and TimeStamp are identical
mismatch_indices = np.where(time_bin_df['TimeStamp'] != time_bin_df['time_stamps'])[0]
print(mismatch_indices)  # Prints indices of rows with non-identical values

[]

In [65]:
time_bin_df = time_bin_df.drop("time_stamps", axis=1)

In [66]:
time_bin_df.head()

,TimeStamp,TimeBin,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,...,Neuron92,Neuron93,Neuron94,x_position,y_position,x_velocity,y_velocity,x_acceleration,y_acceleration,TargetOn
0,23.79,1,0,0,0,0,0,0,0,0,...,0,0,0,-3.528073,1.246197,-0.058506,-0.091257,-27.356562,-17.469933,0
1,23.80,2,0,0,0,0,0,0,0,0,...,0,0,0,-3.528866,1.245791,-0.022758,0.039102,23.217614,13.524994,0
2,23.81,3,0,0,0,0,0,0,0,0,...,0,0,0,-3.528202,1.245970,0.080537,-0.041023,-12.605531,-10.911118,0
3,23.82,4,0,0,0,0,0,0,0,0,...,0,0,0,-3.528681,1.245885,-0.140814,0.072169,-6.628672,17.104540,0
4,23.83,5,0,0,0,0,0,0,0,0,...,1,0,0,-3.528435,1.245922,0.280550,-0.193932,67.613019,-62.822279,0

In [67]:
time_bin_df.describe()

,TimeStamp,TimeBin,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,...,Neuron92,Neuron93,Neuron94,x_position,y_position,x_velocity,y_velocity,x_acceleration,y_acceleration,TargetOn
count,97.000000,97.000000,97.000000,97.0,97.0,97.0,97.000000,97.000000,97.000000,97.000000,...,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,24.270000,49.000000,0.020619,0.0,0.0,0.0,0.041237,0.010309,0.061856,0.061856,...,0.030928,0.010309,0.030928,-2.720505,0.183222,2.596667,-3.544264,-0.208543,0.217659,0.010309
std,0.281455,28.145456,0.142842,0.0,0.0,0.0,0.199871,0.101535,0.242145,0.242145,...,0.174022,0.101535,0.174022,0.889850,1.592618,2.945702,6.143487,42.777120,61.424734,0.101535
min,23.790000,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-3.529861,-2.327198,-0.666423,-15.369152,-135.337590,-104.854105,0.000000
25%,24.030000,25.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-3.452621,-1.655453,0.280550,-8.622702,-21.966568,-50.956382,0.000000
50%,24.270000,49.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-3.126141,1.240234,1.339323,-0.390371,0.144640,-5.700067,0.000000
75%,24.510000,73.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-2.102970,1.444181,4.550276,1.276895,25.852992,41.149836,0.000000
max,24.750000,97.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,-0.998239,1.821541,8.662923,3.709604,135.223619,151.432152,1.000000

In [69]:
trial_info_df.to_csv("trial_comb_info.csv", index=False)

In [70]:
time_bin_df.to_csv("time_bin_comb_info.csv", index=False)