In [1]:
import numpy as np
import pandas as pd

In [2]:
data_df = pd.read_csv("merged_data.csv")
data_df

,Unnamed: 0,TimeBin,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,...,Neuron92,Neuron93,Neuron94,x_position,y_position,x_velocity,y_velocity,x_acceleration,y_acceleration,time_stamps
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,-3.528073,1.246197,-0.058506,-0.091257,-27.356562,-17.469933,23.79
1,1,2,0,0,0,0,0,0,0,0,...,0,0,0,-3.528866,1.245791,-0.022758,0.039102,23.217614,13.524994,23.80
2,2,3,0,0,0,0,0,0,0,0,...,0,0,0,-3.528202,1.245970,0.080537,-0.041023,-12.605531,-10.911118,23.81
3,3,4,0,0,0,0,0,0,0,0,...,0,0,0,-3.528681,1.245885,-0.140814,0.072169,-6.628672,17.104540,23.82
4,4,5,0,0,0,0,0,0,0,0,...,1,0,0,-3.528435,1.245922,0.280550,-0.193932,67.613019,-62.822279,23.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59737,120,121,0,0,0,0,1,0,0,0,...,0,0,0,-4.320620,6.065104,-0.350126,-0.700234,-27.560834,40.023714,1027.78
59738,121,122,0,0,0,0,0,0,0,0,...,0,0,0,-4.323166,6.058218,0.000180,-0.775795,75.348707,-17.292643,1027.79
59739,122,123,0,0,0,0,0,0,0,0,...,0,0,2,-4.320169,6.051746,0.365517,-0.361066,-18.941927,82.073303,1027.80
59740,123,124,0,0,0,0,0,0,0,0,...,1,0,0,-4.319128,6.051788,-0.103370,0.143250,-35.194241,4.807810,1027.81
59741,124,125,0,0,0,0,0,0,0,0,...,0,0,1,-4.320236,6.052351,-0.031825,0.001590,28.280397,-8.170645,1027.82

In [3]:
n_neurons = 94
n_kinem = 4

In [4]:
activity_matrix = data_df.loc[:, 'Neuron1':'Neuron94']
activity_matrix # n_timepoints x n_neurons

,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,Neuron9,Neuron10,...,Neuron85,Neuron86,Neuron87,Neuron88,Neuron89,Neuron90,Neuron91,Neuron92,Neuron93,Neuron94
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59737,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59738,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59739,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
59740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
59741,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
tranposed_activity_matrix = activity_matrix.transpose()
tranposed_activity_matrix # n_neurons x n_timepoints

,0,1,2,3,4,5,6,7,8,9,...,59732,59733,59734,59735,59736,59737,59738,59739,59740,59741
Neuron1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Neuron2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Neuron3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Neuron4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Neuron5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Neuron90,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Neuron91,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Neuron92,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Neuron93,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Neuron94,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,1

In [6]:
kinem_matrix = data_df.loc[:, 'x_velocity':'y_acceleration']
kinem_matrix # n_timepoints x n_kinematics

       x_velocity  y_velocity  x_acceleration  y_acceleration
0       -0.058506   -0.091257      -27.356562      -17.469933
1       -0.022758    0.039102       23.217614       13.524994
2        0.080537   -0.041023      -12.605531      -10.911118
3       -0.140814    0.072169       -6.628672       17.104540
4        0.280550   -0.193932       67.613019      -62.822279
...           ...         ...             ...             ...
59737   -0.350126   -0.700234      -27.560834       40.023714
59738    0.000180   -0.775795       75.348707      -17.292643
59739    0.365517   -0.361066      -18.941927       82.073303
59740   -0.103370    0.143250      -35.194241        4.807810
59741   -0.031825    0.001590       28.280397       -8.170645

[59742 rows x 4 columns]

In [7]:
tranposed_kinem_matrix = kinem_matrix.transpose()
tranposed_kinem_matrix # n_kinematics x n_timepoints

,0,1,2,3,4,5,6,7,8,9,...,59732,59733,59734,59735,59736,59737,59738,59739,59740,59741
x_velocity,-0.058506,-0.022758,0.080537,-0.140814,0.280550,0.486585,-0.068167,0.072590,-0.310723,-0.489965,...,-1.021630,-0.660334,-0.446692,-0.463957,-0.079478,-0.350126,0.000180,0.365517,-0.103370,-0.031825
y_velocity,-0.091257,0.039102,-0.041023,0.072169,-0.193932,-0.501892,0.094395,-0.075410,0.248869,0.521759,...,-1.319538,-1.597277,-1.618220,-1.113867,-1.201935,-0.700234,-0.775795,-0.361066,0.143250,0.001590
x_acceleration,-27.356562,23.217614,-12.605531,-6.628672,67.613019,-37.222080,-30.420010,17.844148,-71.413040,48.720029,...,14.042252,49.123198,-9.625036,28.167124,13.654931,-27.560834,75.348707,-18.941927,-35.194241,28.280397
y_acceleration,-17.469933,13.524994,-10.911118,17.104540,-62.822279,26.407319,41.149836,-32.593504,80.555871,-53.674381,...,33.067605,-57.867053,56.420276,9.511215,16.393488,40.023714,-17.292643,82.073303,4.807810,-8.170645

In [8]:
A = tranposed_activity_matrix.to_numpy() # n_neurons x n_timepoints
Y = tranposed_kinem_matrix.to_numpy() # n_kinematics x n_timepoints

D = np.linalg.lstsq(A @ A.T, A @ Y.T, rcond=None)[0].T
D_reg = np.linalg.lstsq(A @ A.T + A.shape[1] * np.square(np.random.normal(0,20,1)) * np.eye(n_neurons), A @ Y.T, rcond=None)[0].T
Y_hat = D @ A
Y_hat_reg = D_reg @ A

In [21]:
def GetErrors(Y, Y_HAT):
    n = len(Y[0])

    # X VELOCITY RMSE
    x_velocity_rmse = np.sqrt(np.square(np.subtract(Y[0],Y_HAT[0])).mean())

    # Y VELOCITY RMSE
    y_velocity_rmse = np.sqrt(np.square(np.subtract(Y[1],Y_HAT[1])).mean())

    # X ACCELERATION RMSE
    x_acceleration_rmse = np.sqrt(np.square(np.subtract(Y[2],Y_HAT[2])).mean())

    # Y ACCELERATION RMSE
    y_acceleration_rmse = np.sqrt(np.square(np.subtract(Y[3],Y_HAT[3])).mean())

    return (x_velocity_rmse, y_velocity_rmse, x_acceleration_rmse, y_acceleration_rmse)

## Verifying Functional Decoder

In [24]:
functional_error = GetErrors(Y, Y_hat)
print(f"X Velocity RMSE: {functional_error[0]}")
print(f"Y Velocity RMSE: {functional_error[1]}")
print(f"X Acceleration RMSE: {functional_error[2]}")
print(f"Y Acceleration RMSE: {functional_error[3]}")

X Velocity RMSE: 6.416302933793741
Y Velocity RMSE: 6.355657912855544
X Acceleration RMSE: 43.82823510693504
Y Acceleration RMSE: 50.83319516862542

## Verifying L2 Regression

In [25]:
l2_error = GetErrors(Y, Y_hat_reg)
print(f"X Velocity RMSE: {l2_error[0]}")
print(f"Y Velocity RMSE: {l2_error[1]}")
print(f"X Acceleration RMSE: {l2_error[2]}")
print(f"Y Acceleration RMSE: {l2_error[3]}")

X Velocity RMSE: 6.599472849958744
Y Velocity RMSE: 6.565052549502841
X Acceleration RMSE: 44.399326077287
Y Acceleration RMSE: 51.2782400205911